### ISSUE TITLE
There seems to be some bugs

### ISSUE THREAD

**Issue by baishou002** [ilbsm/topoly_tutorial#1]
When I use closure=Closure.MASS_CENTER I get some wrong results

**Comment by baaagr** [comment]
Could you specify or send any example to reproduce the bug?

**Comment by baishou002** [comment]
This is a normal chain, but when I use closure=Closure.MASS_CENTER, it returns me a 3_1.

[test.zip](https://github.com/ilbsm/topoly_tutorial/files/6128357/test.zip)
[knot_for.txt](https://github.com/ilbsm/topoly_tutorial/files/6128358/knot_for.txt)

**Comment by baaagr** [comment]
If you add the first column with atom indexes to the knot_for file, then you will get correct results. 

Nonetheless it should work without index column. We will fix this.

**Comment by prubach** [comment]
@baishou002 thanks very much for reporting the issue. We've fixed this bug and released a new version of topoly (0.9.11). Please test it and let us know if the problem still persists in your case.

BTW, if you change your input file's extension to "xyz" then topoly can directly read it:

`mass_center = homfly('knot_for.xyz',closure=Closure.MASS_CENTER)`

**Comment by baishou002** [comment]
Thank you very much, topoly (0.9.11) should not have this problem afterwards.
