### ISSUE TITLE
M1 wheels not available on PyPi

### ISSUE THREAD

**Issue by Max-Gamill** [ilbsm/topoly_tutorial#2]
Hi there,

I'm interested in using Topoly within one of our own projects to help determine topological species within images, but although the wheels are present for OSX Intel (older Macs) they are not present for ARM (the new M1/M2 Macs).

Are you able to provide wheels for use with M1 architecture on PyPi so I can use Topoly? Or provide access to the source code so we can create a source-based distribution so that if there is not wheel package available for a given architecture, it can be built from source?

Thank you for your help,
Max

**Comment by prubach** [comment]
Version 1.0.1 of topoly provides wheels for M1/M2 Macs.
